FROM idoall/golang:1.12.4
MAINTAINER lion <lion.888@gmail.com>

# COPY files /

RUN go get github.com/idoall/gocryptotrader \
    go get github.com/idoall/gomail \
    go get github.com/idoall/hermes \
    go get github.com/idoall/gods \
    go get github.com/astaxie/beego \
    go get github.com/go-sql-driver \
    go get github.com/gorilla/websocket \
    go get github.com/json-iterator \
    go get github.com/lestrrat/go-file-rotatelogs \
    go get github.com/micro/go-api \
    go get github.com/micro/go-log \
    go get github.com/micro/go-micro \
    go get github.com/rifflock/lfshook \
    go get github.com/sirupsen/logrus \
    go get github.com/uber/jaeger-client-go \
    go get golang.org/x/crypto/scrypt