image: tmaier/docker-compose

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

build_master:
  script:
  - docker-compose build

after_script:
  - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${YOUR_ARTEFACT}:$TAG

variables:
  TAG: ${CI_COMMIT_REF_NAME}
